// Inkbound term bank.
// Each term: [name, tier(1-4 = common/rare/epic/legendary), definition, example, source, alsoPresent[]]
// source: attribution for a real quote, or '' when the example was written for Inkbound.
// alsoPresent: other devices in the same example (never used as wrong answers for it).
// NOTE: definitions and '' examples were written by Claude and have not been checked against a textbook.
const ZONES=[
{id:'fig',name:'Figures of Speech',place:'Mirror Woods',emoji:'🪞',color:'#2F7D6B',
 mobs:[['🦎','Simile Skink'],['🦚','Puffed Peacock'],['🦊','Mirror Fox']],boss:['🐉','The Hyperbole Hydra'],
 terms:[
 ['simile',1,'A comparison using “like” or “as.”','I wandered lonely as a cloud','William Wordsworth',[]],
 ['metaphor',1,'A direct comparison that says one thing is another, without “like” or “as.”','It is the east, and Juliet is the sun.','Shakespeare, Romeo and Juliet',[]],
 ['personification',1,'Giving human qualities or actions to something that isn’t human.','Because I could not stop for Death – / He kindly stopped for me –','Emily Dickinson',['metaphor']],
 ['hyperbole',1,'Extreme exaggeration for effect.','I’ve told you a million times to clean your room.','',[]],
 ['pun',2,'A play on words that uses a word’s double meaning or a similar-sounding word.','We must all hang together, or assuredly we shall all hang separately.','Attributed to Benjamin Franklin',['antithesis']],
 ['understatement',2,'Presenting something as much smaller or less serious than it really is.','After the hurricane flattened his house, he shrugged: “Well, it’s been a rough week.”','',['verbal irony']],
 ['oxymoron',2,'Two contradictory words placed right next to each other.','O brawling love! O loving hate! … O heavy lightness! serious vanity!','Shakespeare, Romeo and Juliet',['apostrophe','paradox']],
 ['extended metaphor',2,'A metaphor that keeps going across several lines or a whole passage.','All the world’s a stage, / And all the men and women merely players; / They have their exits and their entrances','Shakespeare, As You Like It',['metaphor']],
 ['paradox',3,'A statement that seems to contradict itself but reveals a truth.','I must be cruel only to be kind.','Shakespeare, Hamlet',['antithesis']],
 ['metonymy',3,'Referring to something by naming a thing closely connected to it.','The pen is mightier than the sword.','Edward Bulwer-Lytton',[]],
 ['synecdoche',3,'Using a part to stand for the whole (or the whole for a part).','All hands on deck!','',['metonymy']],
 ['apostrophe',3,'Speaking directly to someone absent or dead, or to a thing or idea.','Death, be not proud, though some have called thee / Mighty and dreadful','John Donne',['personification']],
 ['litotes',4,'Understatement that makes a point by denying its opposite.','She just won the state piano competition. “She’s not bad,” her brother admitted.','',['understatement','verbal irony']],
 ]},
{id:'arg',name:'Appeals & Argument',place:'Senate of Stone',emoji:'🏛️',color:'#6B5B95',
 mobs:[['🗿','Stone Senator'],['🦜','Parrot of Pathos'],['🦉','Sophist Owl']],boss:['🦁','The Demagogue Lion'],
 terms:[
 ['ethos',1,'An appeal to the speaker’s credibility or character.','As a nurse with twenty years in the ER, I’ve seen what texting and driving does to people.','',[]],
 ['pathos',1,'An appeal to the audience’s emotions.','Imagine the shelter dog shivering in the cold, waiting for a family that never comes.','',['imagery']],
 ['logos',1,'An appeal to logic, facts, or reasoning.','Schools that moved the first bell to 8:30 saw attendance rise and grades improve, so a later start works.','',['evidence']],
 ['evidence',1,'Facts, data, examples, or quotes used to support a claim.','In a survey of 2,000 students, 64% said they sleep fewer than seven hours on school nights.','',['logos']],
 ['anecdote',1,'A short personal story used to make a point.','Last winter my little brother slipped on the unsalted school steps and broke his wrist. That’s why the walkways need clearing.','',['pathos']],
 ['claim',2,'The main point an arguer wants the audience to accept.','Our school should switch to a four-day week.','',[]],
 ['counterargument',2,'An opposing view that the arguer brings up.','Some will say a later start pushes sports practices into the night.','',[]],
 ['concession',3,'Admitting that the other side has a valid point.','It’s true that a later start would cost the district more in busing.','',['counterargument']],
 ['refutation',3,'Showing why an opposing argument is wrong.','But the district’s own budget report shows busing would cost less than one percent more.','',['logos','evidence']],
 ['kairos',3,'Choosing the right moment or timing to make an argument persuasive.','The morning after the flood, the mayor stood on the broken levee and proposed a new one: “If not now, when?”','',['rhetorical question']],
 ['exigence',4,'The problem or event that prompts someone to speak or write.','After three students were hit at the same crosswalk, a parent wrote to the city council demanding a stoplight.','',[]],
 ['warrant',4,'The unstated assumption that links the evidence to the claim.','Claim: start school later. Evidence: students are sleep-deprived. The unspoken link: well-rested students learn better.','',[]],
 ['rhetorical situation',4,'The full context of an argument: speaker, audience, purpose, occasion, and message.','Before writing her speech, Ava asked: Who am I to them? Who’s listening? Why now? What do I want them to do?','',[]],
 ]},
{id:'snd',name:'Sound & Rhythm',place:'Echo Caves',emoji:'🔔',color:'#3A6EA5',
 mobs:[['🦇','Babble Bat'],['🐸','Croaking Toad'],['🐌','Murmur Snail']],boss:['🐲','The Cacophony Dragon'],
 terms:[
 ['alliteration',1,'Repeating the same consonant sound at the start of nearby words.','Peter Piper picked a peck of pickled peppers.','Nursery rhyme',['consonance']],
 ['onomatopoeia',1,'A word that imitates the sound it describes.','The bacon sizzled and popped while the kettle hissed.','',['imagery']],
 ['rhyme',1,'Matching end sounds in words, often at the ends of lines.','Twinkle, twinkle, little star, / How I wonder what you are!','Jane Taylor',['epizeuxis','meter','couplet']],
 ['assonance',2,'Repeating vowel sounds in nearby words.','The early bird catches the worm.','Proverb',[]],
 ['consonance',2,'Repeating consonant sounds, especially in the middle or at the end of words.','He struck a streak of bad luck.','',['alliteration']],
 ['internal rhyme',2,'Rhyme between words inside the same line.','Once upon a midnight dreary, while I pondered, weak and weary','Edgar Allan Poe, “The Raven”',['meter']],
 ['meter',2,'The pattern of stressed and unstressed syllables in lines of poetry.','da-DUM da-DUM da-DUM da-DUM: every line of the poem keeps the exact same beat.','',[]],
 ['refrain',2,'A line or phrase repeated at regular points in a poem or song.','Stanza after stanza ends on the same line: Quoth the Raven, “Nevermore.”','Edgar Allan Poe, “The Raven”',[]],
 ['iambic pentameter',3,'A line of five iambs: five unstressed-stressed pairs (da-DUM ×5).','Shall I compare thee to a summer’s day?','Shakespeare, Sonnet 18',['meter','rhetorical question']],
 ['enjambment',3,'When a sentence runs past the end of a poetic line into the next with no pause.','I think that I shall never see / A poem lovely as a tree.','Joyce Kilmer, “Trees”',['rhyme','couplet']],
 ['cacophony',3,'Harsh, clashing, unpleasant sounds used for effect.','Grinding gears, cracked kettles, and clattering crates jammed the dock.','',['alliteration','consonance']],
 ['euphony',3,'Smooth, pleasant, musical sounds.','Soft winds lull the willows, and the low river murmurs along.','',['alliteration','personification']],
 ['caesura',4,'A strong pause in the middle of a line of poetry, often marked by punctuation.','To err is human; to forgive, divine.','Alexander Pope',['antithesis','parallelism']],
 ]},
{id:'plot',name:'Plot & Structure',place:'Clockwork Keep',emoji:'⚙️',color:'#8A5A2B',
 mobs:[['🤖','Cog Knight'],['🕷️','Plot Spider'],['🐀','Twist Rat']],boss:['⏰','The Climax Clock'],
 terms:[
 ['setting',1,'The time and place where a story happens.','Chicago, winter of 1893: snow on the rail yards and the World’s Fair glowing by the lake.','',['imagery']],
 ['exposition',1,'The opening part of a story that introduces characters, setting, and background.','The first chapter introduces Maya, her small coastal town, and the bakery her family has run for three generations.','',[]],
 ['conflict',1,'The struggle between opposing forces that drives a story.','Stranded alone after the crash, the pilot battles cold, hunger, and the blizzard to survive.','',[]],
 ['rising action',1,'Events that build tension after the conflict starts and lead up to the climax.','After the first threat letter, things escalate: a break-in, a missing witness, then a second letter naming her sister.','',[]],
 ['climax',1,'The turning point of highest tension in a story.','Final round, two seconds on the clock, she faces her rival with everything riding on one shot.','',[]],
 ['cliffhanger',1,'An ending that leaves the outcome hanging in suspense.','The episode ends as the floor gives way beneath her, and the screen cuts to black.','',[]],
 ['falling action',2,'Events after the climax that wind the tension down.','With the dragon dead, the knights carry the wounded home and start clearing the burned village.','',[]],
 ['resolution',2,'The end of the story, where the conflict is settled (also called the denouement).','A year later, the two brothers have made peace and open the restaurant together.','',[]],
 ['foreshadowing',2,'Hints or clues about what will happen later.','As they set out, the captain eyed the dark clouds and muttered, “I’ve seen a sky like that once before.”','',[]],
 ['subplot',2,'A secondary storyline that runs alongside the main plot.','While the main story follows the murder trial, a second thread follows the lawyer’s daughter learning to drive.','',[]],
 ['red herring',3,'A misleading clue that distracts from the truth.','Every clue points to the creepy gardener, until the cheerful butler turns out to be the killer.','',['situational irony']],
 ['epiphany',3,'A sudden moment of insight or realization for a character.','Staring at the old photo, he finally understood: his father hadn’t abandoned them. He’d been protecting them.','',[]],
 ['deus ex machina',4,'An unlikely, sudden event that conveniently solves a hopeless problem.','Surrounded, out of arrows, no way out, the heroes are saved when giant eagles swoop in out of nowhere.','',[]],
 ]},
{id:'syn',name:'Sentence Power',place:'Forge of Syntax',emoji:'🔨',color:'#B5452E',
 mobs:[['🔥','Comma Sprite'],['🦂','Clause Scorpion'],['🐗','Run-on Boar']],boss:['🐍','The Run-on Serpent'],
 terms:[
 ['rhetorical question',1,'A question asked for effect, not to get an answer.','What, to the American slave, is your 4th of July?','Frederick Douglass',[]],
 ['parallelism',2,'Using the same grammatical structure for a series of words, phrases, or clauses.','He came in prepared, he spoke with confidence, and he left with the deal.','',['tricolon','anaphora']],
 ['anaphora',2,'Repeating the same word or phrase at the start of back-to-back clauses.','It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness','Charles Dickens, A Tale of Two Cities',['antithesis','parallelism']],
 ['syntax',2,'The way words and phrases are arranged into sentences.','Short. Choppy. Fragments. The writer breaks the sentences apart so the chase feels breathless.','',[]],
 ['epistrophe',3,'Repeating the same word or phrase at the end of back-to-back clauses.','government of the people, by the people, for the people, shall not perish from the earth','Abraham Lincoln, Gettysburg Address',['parallelism','tricolon']],
 ['antithesis',3,'Putting contrasting ideas side by side in parallel form.','Give me liberty, or give me death!','Patrick Henry',['parallelism']],
 ['asyndeton',3,'Leaving out the conjunctions between items in a series.','I came, I saw, I conquered.','Julius Caesar',['tricolon','parallelism','anaphora']],
 ['polysyndeton',3,'Using many conjunctions in a row, usually “and.”','We laughed and danced and sang and stayed out until the sun came up.','',[]],
 ['tricolon',3,'A series of three parallel words, phrases, or clauses.','Life, Liberty and the pursuit of Happiness','Declaration of Independence',['parallelism']],
 ['chiasmus',4,'Reversing the order of words or ideas in a second phrase (A-B, B-A).','Ask not what your country can do for you – ask what you can do for your country.','John F. Kennedy, 1961',['antithesis','parallelism']],
 ['anadiplosis',4,'Repeating the last word of one clause at the start of the next.','The storm brought rain, the rain brought floods, the floods brought ruin.','',['parallelism','tricolon']],
 ['epizeuxis',4,'Repeating a word immediately, with nothing in between, for emphasis.','Never, never, never, never, never.','Shakespeare, King Lear',[]],
 ['zeugma',4,'Using one word to govern two others in different senses.','She lost her keys and her temper.','',[]],
 ['periodic sentence',4,'A sentence that holds its main clause until the very end.','Despite the rain, the traffic, and a flat tire two miles out, we made it.','',['tricolon']],
 ['cumulative sentence',4,'A sentence that states the main clause first, then piles on details.','We made it to the stadium, soaked from the rain, worn out from the traffic, laughing about the flat tire.','',['tricolon','parallelism']],
 ]},
{id:'img',name:'Imagery & Symbol',place:'Lantern Gardens',emoji:'🏮',color:'#C08A1E',
 mobs:[['🦋','Motif Moth'],['🐝','Symbol Bee'],['🍄','Shroomling']],boss:['🌳','The Allegory Ent'],
 terms:[
 ['imagery',1,'Descriptive language that appeals to the five senses.','The air smelled of cut grass and rain, and warm yellow light spilled across the porch.','',[]],
 ['theme',1,'The central message or insight about life that a work explores.','Every character who chases money in the novel ends up alone: wealth can’t buy connection.','',[]],
 ['symbol',2,'An object, person, or event that stands for a bigger idea.','Across the bay, the green light at the end of Daisy’s dock stands for everything Gatsby hopes for.','F. Scott Fitzgerald, The Great Gatsby',[]],
 ['allusion',2,'A brief reference to a well-known person, place, event, or work.','Finals week was my Waterloo.','',[]],
 ['connotation',2,'The feelings or associations a word carries beyond its dictionary meaning.','Calling the apartment “cozy” sounds warm; calling the same apartment “cramped” sounds bad.','',['denotation']],
 ['denotation',2,'The literal dictionary meaning of a word.','However it makes you feel, “snake” just means a legless reptile.','',['connotation']],
 ['juxtaposition',2,'Placing two things side by side to highlight their differences.','The billionaire’s yacht docked right beside the shack where the fishermen slept.','',[]],
 ['motif',3,'A recurring image, idea, or element that builds a theme across a work.','Blood keeps coming back in Macbeth: on daggers, on hands that won’t wash clean, in visions, tracking the couple’s guilt.','',['symbol']],
 ['allegory',3,'A story whose characters and events stand for bigger ideas, often moral or political.','In Animal Farm, the animals overthrow the farmer, and each pig and horse stands for a figure of the Russian Revolution.','',['satire']],
 ['archetype',3,'A character, plot, or symbol that repeats across many cultures’ stories.','The wise old mentor who guides the young hero: Merlin, Gandalf, Obi-Wan.','',[]],
 ['conceit',4,'An elaborate, surprising comparison between two very unlike things, often extended.','Donne compares two parted lovers to the legs of a drawing compass: one stays fixed while the other roams, and leans toward it.','John Donne, “A Valediction: Forbidding Mourning”',['extended metaphor','metaphor']],
 ]},
{id:'iro',name:'Irony & Tone',place:'Jester’s Court',emoji:'🃏',color:'#A23B72',
 mobs:[['🐒','Snarky Monkey'],['🎭','Masked Mime'],['🦨','Sour Skunk']],boss:['🤡','The Satire King'],
 terms:[
 ['sarcasm',1,'Mocking, often bitter verbal irony meant to criticize or hurt.','“Oh, great job,” he snapped as his teammate dropped the ball for the third time.','',['verbal irony']],
 ['verbal irony',2,'Saying the opposite of what you actually mean.','Stepping out into the freezing rain, she said, “What lovely weather we’re having.”','',['sarcasm']],
 ['situational irony',2,'When what happens is the opposite of what was expected.','The fire station burned down.','',[]],
 ['dramatic irony',2,'When the audience knows something a character doesn’t.','We know Juliet is only asleep, but Romeo believes she’s dead and drinks the poison.','',[]],
 ['parody',2,'An exaggerated imitation of a work or style for comic effect.','The skit copies a dramatic movie-trailer voice: “In a world… where the dishwasher… is broken…”','',['satire']],
 ['tone',2,'The author’s attitude toward the subject or audience.','The review calls the new policy “a masterpiece of bad timing” and “bold, if you enjoy disasters.” The writer is clearly mocking it.','',['sarcasm','verbal irony']],
 ['mood',2,'The feeling or atmosphere a work creates in the reader.','Fog crept through the empty halls, a door groaned somewhere below, and the candles guttered out one by one.','',['imagery','personification']],
 ['diction',2,'An author’s choice of words.','The writer picks “slaughtered” over “defeated” and “mob” over “crowd” to make the scene feel violent.','',['connotation']],
 ['colloquialism',2,'Informal, everyday language or slang used in writing.','“Y’all fixin’ to head out? Gonna be a hot one today.”','',[]],
 ['euphemism',2,'A mild or polite word used in place of a harsh or blunt one.','The company said it was “letting some employees go” instead of saying it fired them.','',[]],
 ['satire',3,'Using humor, irony, or exaggeration to criticize people or society.','Swift suggested, with a perfectly straight face, that the poor of Ireland sell their babies as food for the rich.','Jonathan Swift, A Modest Proposal',['verbal irony','hyperbole']],
 ['jargon',3,'Specialized language used by a particular group or profession.','We need to leverage our synergies and circle back on the KPIs before the Q3 deep dive.','',[]],
 ['pathetic fallacy',4,'Giving human emotions to nature or weather, often mirroring a character’s mood.','On the day of the funeral, the sky wept and the wind moaned through the trees.','',['personification','mood']],
 ]},
{id:'nar',name:'Narration & Drama',place:'Whispering Library',emoji:'📚',color:'#3D5A80',
 mobs:[['👻','Page Ghost'],['🕯️','Candle Wraith'],['🦉','Night Owl']],boss:['🧙','The Unreliable Wizard'],
 terms:[
 ['first-person point of view',1,'The narrator is a character in the story and uses “I.”','Call me Ishmael.','Herman Melville, Moby-Dick',[]],
 ['flashback',1,'A scene that interrupts the story to show earlier events.','Stepping onto the empty field, she was suddenly eight again, her father cheering from these same bleachers.','',[]],
 ['third-person limited',2,'The narrator uses he/she/they and knows only one character’s thoughts.','Sam stared at the letter. He had no idea who sent it, or why everyone at dinner suddenly went quiet.','',[]],
 ['omniscient narrator',2,'A third-person narrator who knows every character’s thoughts.','Ana thought dinner was going well. Across the table, Marco was planning his escape, and the waiter wondered why neither had touched their food.','',[]],
 ['soliloquy',2,'A speech where a character alone onstage speaks their thoughts aloud.','Alone on the stage, Hamlet wonders aloud, “To be, or not to be, that is the question.”','Shakespeare, Hamlet',['antithesis']],
 ['monologue',2,'A long speech by one character to other characters.','Standing before the crowd at Caesar’s funeral, Mark Antony begins a long speech: “Friends, Romans, countrymen, lend me your ears.”','Shakespeare, Julius Caesar',['synecdoche','metonymy','tricolon']],
 ['unreliable narrator',3,'A narrator whose version of events can’t be fully trusted.','True! – nervous – very, very dreadfully nervous I had been and am; but why will you say that I am mad?','Edgar Allan Poe, “The Tell-Tale Heart”',['first-person point of view','rhetorical question','epizeuxis']],
 ['stream of consciousness',3,'Narration that follows a character’s thoughts as they flow, unfiltered.','coffee’s cold again and the meeting’s at nine or was it ten and why did she look at me like that this morning maybe it’s the shirt','',['polysyndeton']],
 ['in medias res',3,'Starting a story in the middle of the action.','The novel’s first line: “The bullet missed my ear by an inch, and I kept running.”','',['first-person point of view']],
 ['frame narrative',3,'A story told inside another story.','An old sailor at an inn starts telling the guests a tale, and most of the book is that tale.','',[]],
 ['aside',3,'A short remark to the audience that the other characters onstage don’t hear.','As the king raises a toast to him, the villain turns to the audience and mutters, “Enjoy it while it lasts.”','',['dramatic irony']],
 ]},
{id:'fal',name:'Logical Fallacies',place:'Maze of Tricks',emoji:'🌀',color:'#5C7A29',
 mobs:[['🐺','Slippery Wolf'],['🦝','Bandwagon Raccoon'],['🐍','Straw Snake']],boss:['🐙','The Fallacy Kraken'],
 terms:[
 ['bandwagon',1,'Arguing something is right or good because lots of people do it.','Everyone’s buying these sneakers. You need a pair too.','',[]],
 ['ad hominem',2,'Attacking the person instead of their argument.','Why listen to her budget plan? She can’t even keep her own car clean.','',[]],
 ['straw man',2,'Twisting an opponent’s argument into a weaker version that’s easier to attack.','“We should stock fewer sugary drinks in the vending machines.” “So you want to ban all fun from school?”','',['hyperbole']],
 ['slippery slope',2,'Claiming one small step will set off a chain of extreme results.','If we let students use phones at lunch, soon they’ll use them in class, then on tests, and then nobody will learn anything.','',[]],
 ['false dilemma',2,'Presenting only two options when more exist.','Either you’re with us, or you’re against us.','',['antithesis']],
 ['hasty generalization',2,'Jumping to a broad conclusion from too little evidence.','I met two rude people from that town, so everyone there must be rude.','',[]],
 ['circular reasoning',3,'An argument whose conclusion just restates its premise.','This is the best book ever written because no book is better than it.','',[]],
 ['post hoc',3,'Assuming that because one thing happened before another, it caused it.','I wore my lucky socks and we won, so the socks won us the game.','',[]],
 ['false analogy',3,'Comparing two things that aren’t alike in the ways that matter.','Employees are like nails: just as nails have to be hit on the head to work, so do employees.','',['simile']],
 ['appeal to false authority',3,'Citing someone with no real expertise on the topic as proof.','A famous actor says this supplement cures colds, so it must work.','',[]],
 ['appeal to tradition',3,'Arguing something is right because it’s always been done that way.','We’ve always held finals in June, so there’s no reason to change it now.','',[]],
 ['non sequitur',4,'A conclusion that doesn’t follow from what came before.','She’s a great swimmer, so she’d make a terrific class president.','',[]],
 ]},
{id:'chr',name:'Character',place:'Hall of Masks',emoji:'🎭',color:'#7B4B94',
 mobs:[['🧟','Flat Zombie'],['🧛','Foil Vampire'],['👺','Antihero Oni']],boss:['👑','The Tragic King'],
 terms:[
 ['protagonist',1,'The main character at the center of a story.','The whole novel follows Elena as she searches for her missing brother.','',[]],
 ['antagonist',1,'The character or force that opposes the main character.','Every time Elena gets close to the truth, the corrupt sheriff blocks her way.','',[]],
 ['dynamic character',2,'A character who changes in an important way over the story.','Scrooge starts as a miser who hates Christmas and ends as the most generous man in London.','Charles Dickens, A Christmas Carol',['round character']],
 ['static character',2,'A character who stays basically the same throughout the story.','From the first chapter to the last, the grandmother is exactly the same: patient, wise, unshakable.','',[]],
 ['direct characterization',2,'The author states a character’s traits outright.','Mr. Hale was a stingy, impatient man who trusted no one.','',[]],
 ['indirect characterization',2,'Showing a character’s traits through actions, speech, thoughts, or others’ reactions.','Mr. Hale counted the tip twice, sighed, and took back a dollar.','',[]],
 ['foil',3,'A character who contrasts with another, making the other’s traits stand out.','Calm, careful Ben is always paired with his reckless best friend, which makes Ben’s caution stand out even more.','',[]],
 ['round character',3,'A complex, many-sided character.','The detective is brave but insecure, funny but lonely, and her choices keep surprising you.','',['dynamic character']],
 ['flat character',3,'A simple character with only one or two traits.','The bully exists only to sneer and shove people; we learn nothing else about him.','',['static character']],
 ['tragic hero',3,'A great or noble character brought to ruin by a personal flaw.','Oedipus, a great king, is destroyed by his pride and his need to know the truth.','',['hamartia']],
 ['antihero',3,'A main character who lacks typical heroic qualities like goodness or courage.','The story’s lead is a selfish, lying thief who only helps the rebels because they pay him.','',['protagonist']],
 ['hamartia',4,'The tragic flaw or error that causes a hero’s downfall.','Macbeth’s burning ambition is the weakness that drives him to murder and ruin.','',['tragic hero']],
 ]},
{id:'poe',name:'Poetry & Form',place:'Tower of Verse',emoji:'🪶',color:'#2E6E8E',
 mobs:[['🦢','Sonnet Swan'],['🐦‍⬛','Raven'],['🧚','Haiku Sprite']],boss:['🦅','The Epic Eagle'],
 terms:[
 ['stanza',1,'A group of lines that forms a unit in a poem, like a paragraph.','The poem has four sections of four lines each, separated by blank lines.','',['quatrain']],
 ['couplet',1,'Two back-to-back lines, usually rhyming.','So long as men can breathe or eyes can see, / So long lives this, and this gives life to thee.','Shakespeare, Sonnet 18',['rhyme','anaphora','iambic pentameter']],
 ['haiku',1,'A three-line poem with 5, 7, and 5 syllables.','Cold wind on the bay / a gull hangs still in the air / then falls like a stone','',['simile','imagery']],
 ['quatrain',2,'A stanza or poem of four lines.','Each stanza has four lines, rhyming ABAB.','',['stanza']],
 ['sonnet',2,'A 14-line poem, usually in iambic pentameter with a set rhyme scheme.','Fourteen lines of iambic pentameter: three four-line stanzas, then a final rhyming couplet that delivers a twist.','',['iambic pentameter','quatrain','couplet']],
 ['free verse',2,'Poetry with no regular meter or rhyme scheme.','The lines run long, then short, never rhyme, and follow no set beat, just the rhythm of speech.','',[]],
 ['blank verse',3,'Unrhymed iambic pentameter.','Most of Shakespeare’s dialogue is written in unrhymed lines of ten syllables, da-DUM five times.','',['iambic pentameter']],
 ['ode',3,'A formal lyric poem praising and often addressing its subject.','Thou still unravish’d bride of quietness, / Thou foster-child of silence and slow time','John Keats, “Ode on a Grecian Urn”',['apostrophe','metaphor']],
 ['elegy',3,'A poem of mourning for someone who has died.','O Captain! my Captain! our fearful trip is done (written after Lincoln’s assassination)','Walt Whitman',['apostrophe','metaphor']],
 ['epic',3,'A long narrative poem about a hero’s great deeds.','Across twenty-four books, the poem follows Odysseus on his ten-year journey home from the Trojan War.','Homer, The Odyssey',[]],
 ['ballad',3,'A song-like poem that tells a story, often in four-line stanzas.','A poem in four-line stanzas, meant to be sung, telling the tragic story of a sailor lost at sea.','',['quatrain']],
 ]},
];
