// SAT word bank: [word, part of speech, definition, example]. Written by Claude, not verified against an SAT source.
const BANK_RAW=[
["abate","v","to lessen in intensity","The storm began to abate by morning."],
["aberration","n","a departure from what is normal","His bad grade was an aberration, not a pattern."],
["abstain","v","to choose not to do something","She chose to abstain from voting."],
["accommodate","v","to provide room for; to adapt to","The bus can accommodate forty riders."],
["acquiesce","v","to accept something reluctantly without protest","He finally chose to acquiesce to the plan."],
["acrimony","n","bitterness in speech or manner","The debate ended in acrimony."],
["adversity","n","hardship or misfortune","The team stayed calm in the face of adversity."],
["aesthetic","adj","relating to beauty or appearance","The architect cared about the aesthetic value of the lobby."],
["affable","adj","friendly and easy to talk to","The affable coach knew every runner's name."],
["alleviate","v","to make less severe","Ice can alleviate the swelling."],
["ambiguous","adj","open to more than one meaning","The ending of the film was ambiguous."],
["ambivalent","adj","having mixed feelings","He felt ambivalent about moving schools."],
["ameliorate","v","to make something better","New lights helped ameliorate safety on the trail."],
["anachronism","n","something placed in the wrong time period","A wristwatch in a Roman movie is an anachronism."],
["anomaly","n","something that differs from what is normal","The sensor reading was an anomaly."],
["antagonize","v","to make someone hostile","Don't antagonize the referee."],
["apathy","n","lack of interest or concern","Voter apathy kept turnout low."],
["arbitrary","adj","based on random choice rather than reason","The deadline felt arbitrary."],
["arduous","adj","requiring great effort","The climb to the summit was arduous."],
["articulate","adj","able to express ideas clearly","She gave an articulate answer."],
["ascetic","adj","avoiding comfort and pleasure for self-discipline","The monk lived an ascetic life."],
["assiduous","adj","showing careful, persistent effort","Her assiduous practice paid off."],
["audacious","adj","boldly daring","It was an audacious plan to finish in one night."],
["austere","adj","severely plain; without decoration","The room was austere, with one chair and a desk."],
["benevolent","adj","kind and generous","A benevolent donor paid for the new field."],
["bolster","v","to support or strengthen","The data will bolster your argument."],
["brevity","n","shortness of time or speech","The speech was praised for its brevity."],
["cacophony","n","a harsh, jarring mix of sounds","The cafeteria was a cacophony at noon."],
["candor","n","honesty and frankness","I appreciate your candor."],
["capricious","adj","changing suddenly and unpredictably","The capricious weather ruined the hike."],
["castigate","v","to criticize harshly","The editor would castigate sloppy writers."],
["circumspect","adj","careful to consider risks before acting","Be circumspect about what you post online."],
["cogent","adj","clear and convincing","She made a cogent case for a later start time."],
["complacent","adj","too satisfied with yourself to notice danger or improve","The team got complacent after three wins."],
["conciliatory","adj","intended to make peace","He sent a conciliatory text after the argument."],
["conscientious","adj","careful and diligent","A conscientious student checks every answer."],
["conspicuous","adj","easy to notice","The bright helmet made him conspicuous."],
["contrite","adj","feeling sorry for doing wrong","The contrite driver apologized."],
["conundrum","n","a confusing, difficult problem","Choosing a college was a real conundrum."],
["corroborate","v","to confirm with evidence","A second witness can corroborate the story."],
["credulous","adj","too ready to believe things","Only a credulous reader would trust that headline."],
["cursory","adj","quick and not thorough","He gave the essay a cursory glance."],
["dearth","n","a scarcity or lack","There was a dearth of parking downtown."],
["deference","n","respectful yielding to someone else","Out of deference to the judge, they stood."],
["deleterious","adj","harmful","Smoking has deleterious effects on the lungs."],
["deride","v","to mock or ridicule","Critics would deride the movie as boring."],
["diligent","adj","hardworking and careful","A diligent scout earns every badge."],
["disparage","v","to speak of as unimportant or bad","Don't disparage the other team."],
["disparate","adj","very different from each other","The class had disparate opinions."],
["dogmatic","adj","insisting your views are true without question","His dogmatic tone ended the discussion."],
["eclectic","adj","drawn from many different sources","Her playlist is eclectic."],
["efficacy","n","ability to produce the intended result","The study tested the efficacy of the vaccine."],
["egregious","adj","outstandingly bad","That call was an egregious mistake."],
["eloquent","adj","fluent and persuasive in speech or writing","He gave an eloquent speech."],
["elusive","adj","hard to find, catch, or understand","The answer remained elusive."],
["empirical","adj","based on observation or experiment","Scientists need empirical evidence."],
["emulate","v","to copy someone you admire","Young players emulate their heroes."],
["enigmatic","adj","mysterious and hard to understand","She gave an enigmatic smile."],
["ephemeral","adj","lasting a very short time","Fame on social media is ephemeral."],
["equivocal","adj","unclear, often on purpose","The senator gave an equivocal answer."],
["erudite","adj","having great knowledge from study","The erudite professor quoted three languages."],
["exacerbate","v","to make worse","Scratching will exacerbate the rash."],
["exemplary","adj","serving as an excellent example","Her exemplary work earned an award."],
["exonerate","v","to clear of blame","The video helped exonerate the player."],
["expedite","v","to speed up a process","Paying extra will expedite shipping."],
["extraneous","adj","irrelevant or unnecessary","Cut the extraneous details from your essay."],
["fastidious","adj","very attentive to detail and neatness","He is fastidious about his code formatting."],
["fervent","adj","showing intense feeling","The fans were fervent supporters."],
["fortuitous","adj","happening by lucky chance","Their meeting was fortuitous."],
["frugal","adj","careful with money","A frugal shopper waits for sales."],
["futile","adj","pointless; having no effect","Arguing with the vending machine was futile."],
["garrulous","adj","excessively talkative, especially about trivial things","The garrulous passenger talked the whole flight."],
["gregarious","adj","sociable; enjoying company","Her gregarious brother loves big parties."],
["hackneyed","adj","overused and unoriginal","The essay opened with a hackneyed quote."],
["hapless","adj","unlucky","The hapless goalie slipped again."],
["hubris","n","excessive pride or self-confidence","His hubris led to his downfall."],
["iconoclast","n","a person who attacks accepted beliefs","The iconoclast questioned every tradition."],
["idiosyncrasy","n","a peculiar personal habit or trait","Humming while typing is his idiosyncrasy."],
["impetuous","adj","acting quickly without thinking","His impetuous decision cost him the game."],
["inadvertent","adj","not intentional","It was an inadvertent mistake."],
["incessant","adj","never stopping","The incessant rain flooded the street."],
["indifferent","adj","having no interest or concern","She seemed indifferent to the results."],
["indolent","adj","lazy","The indolent cat slept all day."],
["ineffable","adj","too great to be expressed in words","The view from the summit was ineffable."],
["innocuous","adj","harmless","The question seemed innocuous."],
["insipid","adj","dull; lacking flavor or interest","The soup was insipid."],
["intrepid","adj","fearless and adventurous","The intrepid hikers crossed the ridge."],
["inundate","v","to overwhelm with a large amount","Fans would inundate the site with orders."],
["juxtaposition","n","placing things side by side to show contrast","The juxtaposition of old and new buildings was striking."],
["laconic","adj","using very few words","His laconic reply ended the debate."],
["lethargic","adj","sluggish and lacking energy","He felt lethargic after the long flight."],
["loquacious","adj","very talkative","The loquacious tour guide never paused."],
["lucid","adj","clear and easy to understand","She gave a lucid explanation."],
["lucrative","adj","producing a lot of profit","It was a lucrative business."],
["magnanimous","adj","generous, especially toward a rival","The winner was magnanimous in victory."],
["malevolent","adj","wishing harm on others","The villain had a malevolent grin."],
["mercurial","adj","subject to sudden changes of mood","The mercurial artist was hard to work with."],
["meticulous","adj","showing great attention to detail","The model was built with meticulous care."],
["mitigate","v","to make less severe","Helmets mitigate the risk of head injury."],
["mundane","adj","ordinary and dull","Chores are mundane but necessary."],
["nefarious","adj","wicked or criminal","The hackers had a nefarious plan."],
["nonchalant","adj","calm and unconcerned","He seemed nonchalant before the final."],
["obfuscate","v","to make unclear on purpose","Jargon can obfuscate a simple idea."],
["obsolete","adj","no longer used; out of date","Flip phones are nearly obsolete."],
["obstinate","adj","stubbornly refusing to change","The obstinate mule would not move."],
["ostentatious","adj","showy in a way meant to impress","The ostentatious car had gold rims."],
["paradox","n","a statement that seems contradictory but may be true","It's a paradox that less can be more."],
["paucity","n","a small or insufficient amount","There was a paucity of evidence."],
["pedantic","adj","overly focused on minor rules or details","His pedantic corrections annoyed everyone."],
["perfunctory","adj","done with minimal effort, as a routine","She gave a perfunctory wave."],
["pernicious","adj","harmful in a gradual or subtle way","Rumors can have a pernicious effect."],
["placate","v","to calm someone by making concessions","He tried to placate his angry sister."],
["pragmatic","adj","dealing with things in a practical way","We need a pragmatic solution."],
["precocious","adj","showing abilities unusually early","The precocious child read at age three."],
["prodigious","adj","remarkably great in size or degree","She had a prodigious memory."],
["profound","adj","very deep or intense","The book had a profound effect on him."],
["prolific","adj","producing a lot","She was a prolific writer with ten books."],
["propensity","n","a natural tendency","He has a propensity to procrastinate."],
["prudent","adj","acting with care and good judgment","It is prudent to save money."],
["quintessential","adj","the most perfect or typical example","Surfing is the quintessential California sport."],
["rancor","n","deep, bitter resentment","There was no rancor after the loss."],
["recalcitrant","adj","stubbornly uncooperative","The recalcitrant printer refused to work."],
["reconcile","v","to restore friendly relations; to make consistent","They tried to reconcile after the fight."],
["relegate","v","to move to a lower position","The coach would relegate him to the bench."],
["renounce","v","to formally give up","The king chose to renounce the throne."],
["reprehensible","adj","deserving strong criticism","Cheating is reprehensible."],
["resilient","adj","able to recover quickly from difficulty","The resilient team bounced back."],
["reticent","adj","reluctant to share thoughts or feelings","He was reticent about his plans."],
["rhetoric","n","language designed to persuade","The speech was full of empty rhetoric."],
["sanguine","adj","optimistic, especially in a hard situation","She was sanguine about her chances."],
["scrupulous","adj","very careful to do things correctly","A scrupulous accountant checked every number."],
["serendipity","n","finding good things by chance","Finding the cafe was pure serendipity."],
["sporadic","adj","happening at irregular intervals","There was sporadic rain all week."],
["spurious","adj","false or fake","The ad made spurious claims."],
["stoic","adj","enduring pain or hardship without complaint","He stayed stoic despite the injury."],
["substantiate","v","to provide evidence for","Can you substantiate that claim?"],
["superfluous","adj","more than is needed","Remove superfluous words."],
["surreptitious","adj","done secretly","He took a surreptitious look at his phone."],
["tenacious","adj","persistent; not giving up","The tenacious defender never quit."],
["tenuous","adj","very weak or slight","The link between the two events was tenuous."],
["trepidation","n","fear or worry about what might happen","She entered the exam room with trepidation."],
["ubiquitous","adj","found everywhere","Smartphones are ubiquitous."],
["unprecedented","adj","never done or known before","The flood was unprecedented."],
["vacillate","v","to waver between choices","He would vacillate between two colleges."],
["venerate","v","to regard with great respect","Many cultures venerate their elders."],
["verbose","adj","using more words than needed","The verbose essay ran ten pages."],
["vicarious","adj","experienced through someone else","He felt vicarious joy at his brother's win."],
["vindicate","v","to clear of blame or prove right","The results would vindicate her theory."],
["volatile","adj","likely to change suddenly","The stock market is volatile."],
["zealous","adj","full of energetic devotion","A zealous fan painted his face."]
];
